### ISSUE TITLE
Error: Cannot find module '@oclif/plugin-help'

### ISSUE THREAD

**Issue by adamlogic** [heroku/heroku-cli-addons-admin#28]
Hey there. I'm attempting to use this plugin since Kensa is being deprecated, but I'm encountering an error. I installed the plugin via `heroku plugins:install addons-admin`, and I verified that it was installed:

```
❯ heroku help addons:admin    
create and manage add-ons

USAGE
  $ heroku addons:admin

OPTIONS
  -h, --help  show CLI help

COMMANDS
  addons:admin:manifest  manage add-on manifests
  addons:admin:open      open add-on dashboard
```

But when I try to run it, I get the error:

```
❯ heroku addons:admin         
Error: Cannot find module '@oclif/plugin-help'
    at AddonsAdmin._help (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/node_modules/@oclif/command/lib/command.js:98:23)
    at AddonsAdmin.run (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/lib/commands/addons/admin.js:7:14)
    at AddonsAdmin._run (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/node_modules/@oclif/command/lib/command.js:29:31)
```

Attempting to install `@oclif/plugin-help` didn't fix it:

```
❯ npm install -g @oclif/plugin-help
+ @oclif/plugin-help@2.1.2
added 31 packages in 3.684s

❯ heroku addons:admin              
Error: Cannot find module '@oclif/plugin-help'
    at AddonsAdmin._help (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/node_modules/@oclif/command/lib/command.js:98:23)
    at AddonsAdmin.run (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/lib/commands/addons/admin.js:7:14)
    at AddonsAdmin._run (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/node_modules/@oclif/command/lib/command.js:29:31)
```

I'm running Node 9.6.1 on macOS 10.13.6.

Any pointers on what to try next?

**Comment by as-roman-o** [comment]
I have the same issue
```
Error: Cannot find module '@oclif/plugin-help'
    at AddonsAdmin._help (~/.local/share/heroku/node_modules/@oclif/command/lib/command.js:101:23)
    at AddonsAdmin.run (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/lib/commands/addons/admin.js:7:14)
    at AddonsAdmin._run (~/.local/share/heroku/node_modules/@oclif/command/lib/command.js:29:31)
```
heroku version `heroku/7.18.3 linux-x64 node-v10.12.0`
node version `v10.12.0`
Ubuntu 16.04

**Comment by RasPhilCo** [comment]
We have a major version update coming soon that will fix this, for now ignore it and pardon our dust.

**Comment by RasPhilCo** [comment]
`v2.0.0` has been released, if installed, run `heroku update` to update.

**Comment by adamlogic** [comment]
👍 I can confirm that it works now.

Note that it initially failed because my manifest was named `addon-manifest.json` instead of `addon_manifest.json`:

```
❯ heroku addons:admin:open
Error: Check if addon_manifest.json exists in root. 
 Error: ENOENT: no such file or directory, open 'addon_manifest.json'
    at Object.run (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/lib/manifest.js:49:19)
    at Object.json (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/lib/manifest.js:57:38)
    at Object.slug (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/lib/manifest.js:68:37)
    at Open.run (~/.local/share/heroku/node_modules/@heroku-cli/plugin-addons-admin/lib/commands/addons/admin/open.js:9:46)
    at Open._run (~/.local/share/heroku/node_modules/@oclif/command/lib/command.js:29:31)
```

This file has existed so long, I can't remember if I named it that or if Kensa did. If it was Kensa, I'm sure lots of other folks will run into this.

It worked fine after I renamed the file.

**Comment by ransombriggs** [comment]
I am re-opening so that the `addon_manifest.json` workaround is visible while I work on a fix

**Comment by ransombriggs** [comment]
@adamlogic thanks for reporting the issue between `addon_manifest.json` & `addon-manifest.json`.  I have fixed this bug so that it will use `addon-manifest.json` so as not to confuse future users.  Could you update your plugin with this command? 
```
heroku plugins:update
```
After it updates you will start seeing a deprecation notice around `addon_manifest.json` existing, so just rename it to `addon-manifest.json` and it should go away.

**Comment by adamlogic** [comment]
👍 Updated and verified. Thanks for the fix!

**Comment by ransombriggs** [comment]
Good to hear and thanks again for reporting!
